### ISSUE TITLE
Is the RDX-RP2040 not limited to digital models in the future?

### ISSUE THREAD

**Issue by Trendyfu** [lu7did/RDX-rp2040#23]
Hi, lu7did
The waterfall on this RDX-RP2040 is so cool.
Do you plan to add SSB,CW, AM, FM and other modes to it in the future?

**Comment by lu7did** [comment]
Hi!
No, the RDX-rp2040 firmware will only support FT8. I'm working on a version of the ADX-rp2040 (ADX-rp2040-mbed) which supports the RDX board, this version of the firmware is slave from a PC based program (as the ADX board is), so it will depend on what the PC program sends over the audio channel (this version also supports audio over USB). In this regard it's likely you can use the board to listen to other modes. However the TX chain will only support PSK modes because of the class H finals it uses (no amplitude modulation performed). But this is the firmware I'm making and supporting, nothing prevents anybody to hack their own firmware on the board to do as they please, it's an experimentation project.

73 de Pedro, LU7DZ
